### ISSUE TITLE
Method of using without API Key?

### ISSUE THREAD

**Issue by driscoll42** [isaactbock/library-scan#12] opened 2021-09-24 21:17 UTC
Whenever I try to download the extension on the Google Chrome Store, it will not let me. It claims it is already installed, and even though it isn't it won't let me install it.

![image](https://user-images.githubusercontent.com/4751505/134740446-3a1a7af8-fe28-4704-b33b-04208729ebae.png)

To get around this I attempted to download the source code and load the extension manually. When I did it gave me an error about the missing "background/api_keys.js" file. Which makes sense you wouldn't store an api key on GitHub. I deleted that line and was able to install the extension, but obviously I can't use it without the api keys.

I was going to open a ticket about including a format to insert your own API keys, but I see that Goodreads is depreciating their API. Given that one day the Goodreads API will terminate, is there a way to use this without it? I could export my collection and the extension could read the file, or perhaps scrape Goodreads? 

Or at least if there is some way to download the extension that would work as well for me. This extension seems awesome and I would love to able to use it.

**Comment by isaacbock** [comment] 2021-09-28 05:16
Hi! So glad you found Library Scan, and sorry for the troubles installing! I encountered the exact same problem while reproducing the issue this week (thanks for bringing it to my attention!) and after some digging, it seems like there were some issues with the Chrome Web Store that have since been fixed on their end. 

Fortunately, no new versions of the extension have been released during this time frame and installation is working again on my end, so everything should hopefully be good to go if you'd like to give it another try!

Otherwise, if downloading still isn't working, I'd love to keep troubleshooting and can also publish a packaged version of the extension (w/ API keys and/or api_keys.js documentation) to temporarily bridge the gap.

Thanks so much, and good luck!

**Comment by driscoll42** [comment] 2021-09-28 12:05
Your fix to the Chrome webstore worked! And this is awesome! Saved me quite a bit of time of trying out books on Overdrive, only found 10 books but I have semi-obscure interests, would have been irritating trying 190 times and finding nothing. Thank you for your help!

The only other features I could think that would make this even better would be to go beyond 200 books and more libraries, though the former is most useful. Looking at the Goodreads URL, there's a "&page=2" that could be added to the to read list URL and then some kind of while look that checks if there's books or not and if not breaks should work. I'm not a javascript developer but I might give this a shot at some point in the future when I have time.

Anyway, this is fixed for now. If you need any help with someone testing out a change in the future, please feel free to let me know.

**Closed as completed** 2021-09-28 12:20 UTC
